#create a note
POST http://localhost:4500/notebook
Content-Type: application/json

{
    "note_title": "Smile a little",
    "content": "It works, don’t touch!"
}

###
#fetch whole notebook
GET http://localhost:4500/notebook


###
#fetch a single note
GET http://localhost:4500/notebook/94309207-5445-4299-bcf3-558016e7d183

###
#update a note by its id
POST http://localhost:4500/notebook/94309207-5445-4299-bcf3-558016e7d183
Content-Type: application/json

{
    "note_title": "Bryson Potts Note",
    "content": "I be silent on it but I keep on smilling"
}


###
#delete note by its id
DELETE  http://localhost:4500/notebook/58dc7b3b-00ec-40e8-b5ce-6ab91e3434f1
